### ISSUE TITLE
datetime/timestamp issue

### ISSUE THREAD

**Issue by fivetran-kristin** [fivetran/dbt_mixpanel#11]
From email:

Hi Guys,

Just another thing that is hampering me right now. I am using the Mixpanel dbt package from Fivetran, but I am running into and error when using it:

Looking at the executed code this is the part that is causing the error:
occurred_at >= coalesce((select cast( max(date_day) as  
    timestamp

Looking at the source schema, which is “stg_mixpanel__event_tmp” the “time” column, which is renamed in a CTE, is of type DATETIME. This means that we are trying to do a “‘DATETIME' >= ’TIMESTAMP’” which isn’t allowed in BigQuery.

And then looking at the code in GitHub this appears to be the effected line:
https://github.com/fivetran/dbt_mixpanel/blob/f1d866fbca238ba194cdcdeed9b897c480620c6e/models/mixpanel__event.sql#L22

I am unsure myself how to fix this since this code will run across multiple database systems.

Can this be raised with your dbt team please? Unfortunately this is really blocking me right now, so going to have to find a workaround

Thanks,

Craig

**Comment by fivetran-kristin** [comment]
@fivetran-jamie can you pleas look into this ASAP and see what's going on?

**Comment by fivetran-jamie** [comment]
yeah this is kind of strange because the `time`/`occurred_at` column is a timestamp in our source data. i'll refactor the staging model to explicitly cast it as a timestamp and we can ask the user to try it out

**Comment by fivetran-jamie** [comment]
@fivetran-kristin  i opened a [PR](https://github.com/fivetran/dbt_mixpanel/pull/12) on the `occurred_at_fix` branch, if you could review/ask the customer to test it out 🤠

**Comment by fivetran-jamie** [comment]
closing this -- merged the PR after the customer tested it out, and pushing a new mixpanel release today
