### ISSUE TITLE
allow for casting/aliasing custom columns

### ISSUE THREAD

**Issue by fivetran-kristin** [fivetran/dbt_mixpanel#15]
Slack thread here: https://getdbt.slack.com/archives/CBSQTAPLG/p1619707327482400

**Comment by fivetran-jamie** [comment]
after talking with Julie it seems like our new way of handling passthrough columns ([described here](https://github.com/fivetran/dbt_klaviyo#passthrough-columns)) solves this issue. pr coming shortly...
