### ISSUE TITLE
Package fails if custom event properties contains spaces

### ISSUE THREAD

**Issue by Abraflare** [fivetran/dbt_mixpanel#4]
I have recently started to use Mixpanel with our company and went to use this dbt package.

Using the `event_properties_to_pivot` configuration I have added 4 different properties, each of which contain spaces. This has cause the SQL that is executed to be incorrect and not run as the column name in the `AS` definition are not quoted e.g.

```
replace(parse_json(event_properties):Company Name, '"', '') as Company Name,
replace(parse_json(event_properties):Region Code, '"', '') as Region Code,
```

Environment:
dbt environment - dbt cloud
destination - Snowflake DB
Package version - 0.1.0

**Comment by Abraflare** [comment]
Tested locally and changing the `pivot_event_properties_json.sql` macro and changing the Snowflake line to:

```
{%- elif target.type == 'snowflake' -%}
replace(parse_json(event_properties):"{{ property }}", '"', '') as "{{ property }}"
```

Fixes the issue and will be compatible with properties with spaces and no spaces.

**Comment by fivetran-jamie** [comment]
We've just released the fix for this issue in version 0.1.1. I'll ping this thread when it's up on dbt hub!

**Comment by Abraflare** [comment]
Thanks so much for looking into this and actioning so quickly

**Comment by fivetran-jamie** [comment]
new release is on the hub [here](https://hub.getdbt.com/fivetran/mixpanel/latest/)!
