### ISSUE TITLE
Any chance of supporting Postgres?

### ISSUE THREAD

**Issue by nikhilro** [fivetran/dbt_mixpanel#8]
Hey Fivetran team,

Been loving Fivetran connectors and dbt transformers on top of those connectors. Set up our Stripe to use them and have very clean data that we can use in our dashboards. 

Wanted to do the same for our Mixpanel data but unfortunately, this package doesn't work for Postgres. Looking at it, there seem to be only a few things that make this incompatible with Postgres like how the interval is formatted and using `alias` after `FROM`. Any chance you'd support Postgres, please?

Thanks for considering,
Nikhil

**Comment by fivetran-kristin** [comment]
Hey Nikhil,

We recently made some changes to hopefully make this package compatible for Postgres.  I don't have Postgres set up, so can't test on my side, but I *think* we're close.  Can you test the package by installing a branch of this package using the following syntax:

```
packages:
  - git: "https://github.com/fivetran/dbt_mixpanel.git"
    revision: postgres_testing

```

Once you add this to your `packages.yml` file, you will need to run `dbt clean` and then `dbt deps`.

Let me know how it goes, thanks!

**Comment by nikhilro** [comment]
Hey Kristen, 

Awesome to have you trying to support Postgres, thanks very much!

Tried after updating the packages. This is the error:
```
Database Error in model mixpanel__event (models/mixpanel__event.sql)
  subquery in FROM must have an alias
  LINE 298:     select * from (
                              ^
  HINT:  For example, FROM (SELECT ...) [AS] foo.
  compiled SQL at target/compiled/mixpanel/models/mixpanel__event.sql

Database Error in model stg_mixpanel__user_event_date_spine (models/staging/stg_mixpanel__user_event_date_spine.sql)
  subquery in FROM must have an alias
  LINE 19:     from (
                    ^
  HINT:  For example, FROM (SELECT ...) [AS] foo.
  compiled SQL at target/run/mixpanel/models/staging/stg_mixpanel__user_event_date_spine.sql
```

Happy to do a live debugging session with you if that's easier. Here's my calendly: https://calendly.com/s-nikhil/personal

**Comment by fivetran-jamie** [comment]
hey @nikhilro -- i think i've got this working! could you install and try out the following branch of the package:
```
packages:
  - git: "https://github.com/fivetran/dbt_mixpanel.git"
    revision: jr_working
 ```

**Comment by nikhilro** [comment]
Might be some wrong configuration on my end but get this error after adding that ^

```
Encountered an error:
Database Error
  permission denied for database sp
```

**Comment by fivetran-jamie** [comment]
hm that might be an issue with your target profile permissions. happy to do a live debugging session together to get this working!

**Comment by nikhilro** [comment]
Let's do it, here's my calendly: http://calendly.com/s-nikhil/personal if that's easier

**Comment by fivetran-jamie** [comment]
sweet, booked 3pm PST today
